kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: dtabs.l5d.io
spec:
  scope: Namespaced
  group: l5d.io
  version: v1alpha1
  names:
    kind: DTab
    plural: dtabs
    singular: dtab
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: namerd-config
data:
  config.yml: |-
    admin:
      ip: 0.0.0.0
      port: 9991
    namers:
    - kind: io.l5d.k8s
      prefix: /io.l5d.k8s.out
      host: localhost
      port: 8001
    - kind: io.l5d.k8s
      prefix: /io.l5d.k8s.in
      host: localhost
      port: 8001
    - kind: io.l5d.rewrite
      prefix: /portNsSvcToK8s
      pattern: "/{port}/{ns}/{svc}"
      name: "/k8s/{ns}/{port}/{svc}"
    storage:
      kind: io.l5d.k8s
      host: localhost
      port: 8001
      namespace: default
    interfaces:
    - kind: io.l5d.httpController
      ip: 0.0.0.0
      port: 4180
    - kind: io.l5d.mesh
      ip: 0.0.0.0
      port: 4321
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: namerd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namerd
  template:
    metadata:
      labels:
        app: namerd
    spec:
      dnsPolicy: ClusterFirst
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: "NoSchedule"
      nodeName: kube-master
      volumes:
      - name: namerd-config
        configMap:
          name: namerd-config
      containers:
      - name: namerd
        image: buoyantio/namerd:1.3.6
        args:
        - /io.buoyant/namerd/config/config.yml
        ports:
        - name: http
          containerPort: 4180
        - name: mesh
          containerPort: 4321
        - name: admin
          containerPort: 9991
          hostPort: 9991
        volumeMounts:
        - name: "namerd-config"
          mountPath: "/io.buoyant/namerd/config"
          readOnly: true
      - name: kubectl
        image: zhanyang/kubectl:1.9.3
        args:
        - "proxy"
        - "-p"
        - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: namerd
spec:
  selector:
    app: namerd
  type: ClusterIP
  ports:
  - name: http
    port: 4180
  - name: mesh
    port: 4321
  - name: admin
    port: 9991
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: namerctl-script
data:
  createNs.sh: |-
    #!/bin/sh
    set -e
    if namerctl dtab get outgoing > /dev/null 2>&1; then
      echo "outgoing namespace already exists"
    else
      echo "
      /k8s          =>   /#/io.l5d.k8s.out;
      /portNsSvc    =>   /#/portNsSvcToK8s;
      /host         =>   /portNsSvc/http/default;
      /host         =>   /portNsSvc/http;
      /svc          =>   /$/io.buoyant.http.domainToPathPfx/host;
      " | namerctl dtab create outgoing -
    fi
    if namerctl dtab get incoming > /dev/null 2>&1; then
      echo "incoming namespace already exists"
    else
      echo "
      /k8s          =>   /#/io.l5d.k8s.out;
      /portNsSvc    =>   /#/portNsSvcToK8s;
      /host         =>   /portNsSvc/http/default;
      /host         =>   /portNsSvc/http;
      /svc          =>   /$/io.buoyant.http.domainToPathPfx/host;
      " | namerctl dtab create incoming -
    fi
---
kind: Job
apiVersion: batch/v1
metadata:
  name: namerctl
spec:
  template:
    metadata:
      name: namerctl
    spec:
      volumes:
      - name: namerctl-script
        configMap:
          name: namerctl-script
          defaultMode: 0755
      containers:
      - name: namerctl
        image: linkerd/namerctl:0.8.6
        env:
        - name: NAMERCTL_BASE_URL
          value: http://namerd.default.svc.cluster.local:4180
        command:
        - "/namerctl/createNs.sh"
        volumeMounts:
        - name: "namerctl-script"
          mountPath: "/namerctl"
          readOnly: true
      restartPolicy: OnFailure