---
apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d-config-egress
data:
  config.yaml: |-
    admin:
      ip: 0.0.0.0
      port: 9990
    telemetry:
    - kind: io.l5d.prometheus
    - kind: io.l5d.recentRequests
      sampleRate: 0.25
    usage:
      enabled: false
    routers:
    - protocol: http
      label: outgoing
      dtab: |
        /egress       =>   /$/io.buoyant.rinet;
        /svc          =>   /egress/443;
        /svc          =>   /$/io.buoyant.porthostPfx/egress;
      servers:
      - port: 4140
        ip: 0.0.0.0
      client:
        kind: io.l5d.static
        configs:
        - prefix: "/$/io.buoyant.rinet/443/{service}"
          tls:
            commonName: "{service}"
      service:
        responseClassifier:
          kind: io.l5d.http.retryableRead5XX
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: l5d-egress
  name: l5d-egress
spec:
  selector:
    matchLabels:
      app: l5d-egress
  template:
    metadata:
      labels:
        app: l5d-egress
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: "NoSchedule"
      nodeName: kube-master
      volumes:
      - name: l5d-config-egress
        configMap:
          name: "l5d-config-egress"
      containers:
      - name: l5d-egress
        image: buoyantio/linkerd:1.3.6
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
        - /io.buoyant/linkerd/config/config.yaml
        ports:
        - name: outgoing
          containerPort: 4140
          hostPort: 4140
        - name: admin
          containerPort: 9990
          hostPort: 9990
        volumeMounts:
        - name: "l5d-config-egress"
          mountPath: "/io.buoyant/linkerd/config"
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: l5d-egress
spec:
  selector:
    app: l5d-egress
  clusterIP: None
  ports:
  - name: outgoing
    port: 4140
  - name: admin
    port: 9990